### ISSUE TITLE
Missing ECJ and MyMASON from build path

### ISSUE THREAD

**Issue by sauravrt** [xueyizou/ACASX_3D#1]
Could you please add the two missing projects to this repository.

**Comment by xueyizou** [comment]
For ECJ, you can find it from https://cs.gmu.edu/~eclab/projects/ecj/.
I have added MyMASON to GitHub, you can find it from https://github.com/xueyizou/MyMASON.git. I made some minor changes to the original MASON (http://cs.gmu.edu/~eclab/projects/mason/), resulting in MyMASON. 
For the use of these two libraries, please refer to their websites.

**Comment by sauravrt** [comment]
Thanks
